version: '1.0'

services:
  main:
    build: ./ros
    restart: always
    network_mode: host
    privileged: true
    environment:
            - UDEV=1
    devices:
            - "/dev:/dev"
